export const PreferencesKeys = {
    authToken: `authToken`,
    accessToken: `accessToken`,
    idToken: `idToken`,
    ssoDiscovery: `discovery`,
    ssoAuthConfig: `authConfig`,
    id: `id`,
    customerCars: "customerCars",
    selectedCar: "selectedCarId",
    catName: "catName",
    subCatName: "subCatName",
    Brands: "Brands",
    dynamiFilters: "dynamiFilters",
    categoryList: "HomeCat",
    brands: "Brands",
    cards: "cards",
    banks: "banks",
    stores: "stores",
    searchedKeywords: "historyKeyWords",
    userDetails: "userDetails",
    userResume: "userResume",
    userJobType: "jobType",
    quantity: "quantity",
    notificationGetTime: 'notificationGetTime',
    jobInfoSyncTime: 'JobInfoSyncTime',
    shiftDetail: 'shiftDetail'
};
