export const images = {
  thumbsUp: require('./../assets/images/thumbsUp.png'),
  notification: require('./../assets/images/notification.png'),
  dummy: require('./../assets/images/dummy.png'),
  profile: require('./../assets/images/profile.png'),
  arrowForward: require('./../assets/images/arrowForward.png'),
  clock: require('./../assets/images/clock.gif'),
  time: require('./../assets/images/time.png'),
  info: require('./../assets/images/info.png'),
  check: require('./../assets/images/check.png'),
  reject: require('./../assets/images/reject.png'),
  arrowBack: require('./../assets/images/arrowBack.png'),
  cameraIcon: require('./../assets/images/cameraIcon.png'),
  check1: require('./../assets/images/check1.png'),
  attach: require('./../assets/images/attach.png'),
  cross: require('./../assets/images/cross.png'),
  question: require('./../assets/images/question.png'),
  listImage: require('../../assets/list.png'),
};
